package d3;
final class metrics{
	public static int cam_btm;
	public static int cam_clip_btm;
	public static int cam_clip_front;
	public static int cam_clip_left;
	public static int cam_clip_right;
	public static int cam_clip_top;
	public static int cam_cull_btm;
	public static int cam_cull_front;
	public static int cam_cull_left;
	public static int cam_cull_ms;
	public static int cam_cull_right;
	public static int cam_cull_top;
	public static int cam_front;
	public static int cam_gnd_ms;
	public static int cam_left;
	public static int cam_obj_ms;
	public static int cam_objq;
	public static int cam_rend_ms;
	public static int cam_rendtot;
	public static int cam_right;
	public static int cam_sky_ms;
	public static int cam_sort_ms;
	public static int cam_top;
	public static int[] coldet=new int[2];
	public static int[] coldethit=new int[2];
	public static int grd_put;
	public static int grd_take;
	public static int obj_rend_clp;
	public static int obj_rend_clpno;
	public static int obj_rend_cull_proj;
	public static int rend_noclp;
	public static int rend_npoly;
	public static int[] rend_poly_clp=new int[5];
	public static int rend_poly_clp_allandbtm;
	public static int rend_poly_clp_allandlft;
	public static int rend_poly_clp_allandrht;
	public static int rend_poly_clp_allandtop;
	public static int rend_poly_clp_allandz;
	public static int[] rend_poly_clp_cull=new int[5];
	public static int rend_poly_clp_cullcf;
	public static int rend_poly_clp_znearcull;
	public static int rend_poly_clpno;
	public static int wld_coldet_ms;
	public static int wld_colhdl_ms;
	public static int wld_paint_ms;
	public static int wld_upd_ms;
	public static int wld_updgrds_ms;
	public static int net_rec_dt;
	public static int net_send_dt;	
}
